### ISSUE TITLE
Custom Styling

### ISSUE THREAD

**Issue by josephgupkim** [ecipra/colmar-academy#3]
I liked the addition of the custom styling to your Colmar project and my only "issue" is that I wish you added more! This would've been an awesome opportunity to showcase everything you've learned and make this project your own. 
Other than that, great choices on the colors and font choice!

**Comment by ecipra** [comment]
This is one of those places where I'm not actually sure what y'all want. I've gotten dinged on stepping away from spec and then dinged again for not stepping far enough away from spec. It would be nice if the Codecademy team could make their expectations more transparent in future iterations of the class.
